LanchesMac/Models/Lanche.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LanchesMac.Models
{
    [Table("Lanches")]
    public class Lanche
    {
        [Key]
        public int LancheId { get; set; }
        
        [Required(ErrorMessage ="O nome do lanche deve ser informado")]
        [Display(Name = "Nome do Lanche")]
        [StringLength(80, MinimumLength =10, ErrorMessage = "O {0} deve ter no mínimo {1} e no máximo {2}")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "A descrição do lanche deve ser informada")]
        [Display(Name = "Descrição do Lanche")]
        [MinLength(20, ErrorMessage = "Descrição deve ter no mínimo {1} caracteres")]
        [MaxLength(200, ErrorMessage = "Descrição deve ter no máximo {1} caracteres")]
        public string DescricaoCurta { get; set; }

        [Required(ErrorMessage = "A descrição detalhada do lanche deve ser informada")]
        [Display(Name = "Descrição detalhada do Lanche")]
        [MinLength(20, ErrorMessage = "Descrição detalhada deve ter no mínimo {1} caracteres")]
        [MaxLength(200, ErrorMessage = "Descrição detalhada deve ter no máximo {1} caracteres")]
        public string DescricaoDetalhada { get; set; }

        [Required(ErrorMessage = "Informe o preço do lanche")]
        [Display(Name = "Preço")]
        [Column(TypeName ="decimal(10,2)")]
        [Range(1,999.99, ErrorMessage ="O preço deve estar entre 1 e 999,99")]
        public decimal Preco { get; set; }

        [Display(Name = "Caminho Imagem Normal")]
        [StringLength(200, ErrorMessage = "O {0} deve ter no máximo {1}")]
        public string ImagemUrl { get; set; }

        [Display(Name = "Caminho Imagem Miniatura")]
        [StringLength(200, ErrorMessage = "O {0} deve ter no máximo {1}")]
        public string ImagemThumbnailUrl { get; set; }

        [Display(Name = "Preferido?")]
        public bool IsLanchePreferido { get; set; }

        [Display(Name = "Estoque")]
        public bool EmEstoque { get; set; }

        //[NotMapped]
        //public DateTime DataDeCriacao { get; set; }

        [Display(Name = "Categorias")]
        public int CategoriaId { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}

LanchesMac/Controllers/CarrinhoCompraController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
            //return View();
        }

        /*
        RedirectToActionResult:
        -302 - Found
        -301 - Moved Permanently
        -307 - Temporaty Redirect
        -308 - Permanent Redirect
        */

        [Authorize]
        public IActionResult AdicionarItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p => p.LancheId == lancheId);

            if (lancheSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult RemoverItemDoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p => p.LancheId == lancheId);

            if (lancheSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }

    }
}

LanchesMac/Controllers/LancheController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if(string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(l => l.LancheId);
                categoriaAtual = "Todos os lanches";
            } 
            else
            {
                //if(string.Equals("Normal", categoria, StringComparison.OrdinalIgnoreCase))
                //{
                //    lanches = _lancheRepository.Lanches.Where(l => l.Categoria.CategoriaNome.Equals("Normal")).OrderBy(l => l.Nome);
                //}
                //else
                //{
                //    lanches = _lancheRepository.Lanches.Where(l => l.Categoria.CategoriaNome.Equals("Natural")).OrderBy(l => l.Nome);
                //}
                lanches = _lancheRepository.Lanches
                            .Where(l => l.Categoria.CategoriaNome.Equals(categoria))
                            .OrderBy(c => c.Nome);
                categoriaAtual = categoria;
            }

            var lanchesListViewModel = new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };

            return View(lanchesListViewModel);
        }

        public IActionResult Details(int lancheId)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(l => l.LancheId == lancheId);
            return View(lanche);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if(string.IsNullOrEmpty(searchString))
            {
                lanches = _lancheRepository.Lanches.OrderBy(p => p.LancheId);
                categoriaAtual = "Todos os Lanches";
            }
            else
            {
                lanches = _lancheRepository.Lanches.Where(p => p.Nome.ToLower().Contains(searchString.ToLower()));
                if (lanches.Any())
                {
                    categoriaAtual = "Lanches";
                }
                else
                {
                    categoriaAtual = "Nenhum lanche foi encontrado";
                }
            }

            return View("~/Views/Lanche/List.cshtml", new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            });
        }

            //public IActionResult List()
            //{
            //    //ViewData["Titulo"] = "Todos os Lanches";
            //    //ViewData["Data"] = DateTime.Now;
            //
            //    //var lanches = _lancheRepository.Lanches;
            //    //var totalLanches = lanches.Count();
            //
            //    //ViewBag.Total = "Total de lanches : ";
            //    //ViewBag.TotalLanches = totalLanches;
            //
            //    //return View(lanches);
            //    var lanchesListViewModel = new LancheListViewModel();
            //    lanchesListViewModel.Lanches = _lancheRepository.Lanches;
            //    lanchesListViewModel.CategoriaAtual = "Categoria Atual";
            //
            //    return View(lanchesListViewModel);
            //}
        }
}

LanchesMac/Views/Lanche/Details.cshtml
@model Lanche

<div class="container">
    <div class="row">
        <div class="card">
            <div class="text-center">
                <img src="@Model.ImagemUrl" class="img-fluid" alt="" />
            </div>
            @*<div class="card-block">*@
            <div class="card-body">
                <h2 class="card-title">@Model.Nome</h2>
                <p class="card-text"><h5>@Model.DescricaoDetalhada</h5></p>

                <p class="btn btn-group align-content-lg-end">
                    <a asp-controller="Lanche" asp-action="List" class="btn btn-outline-info">Ver todos os lanches</a>
                    <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-lancheId="@Model.LancheId">Adicionar @Model.Nome ao carrinho</a>
                </p>

            </div>

        </div>
    </div>
</div>

LanchesMac/Views/Lanche/List.cshtml
@*@model IEnumerable<LanchesMac.Models.Lanche>*@
@model LancheListViewModel

@*@{
    ViewData["Title"] = "Lista de lanches";
}*@

@*<div>
    <h2>@ViewData["Titulo"]</h2>
</div>
<h2>@ViewData["Data"]</h2>
<hr />
<h3>@ViewBag.Total @ViewBag.TotalLanches</h3>
<hr />*@
<div><h2>@Model.CategoriaAtual</h2></div>

@*<h1>@TempData["Nome"]</h1>*@

<div class="container">
    <div class="row">
        @foreach (var lanche in Model.Lanches)
        {
            <partial name="_LanchesResumo" for="@lanche" />
            @*<div class="col-sm-4 col-md-4 col-lg-4">
                <p><img src="@lanche.ImagemUrl" class="img-fluid"></p>
                <h3>Preço : @lanche.Preco.ToString("c")</h3>
                <h4>@lanche.Nome</h4>
                <p>@lanche.DescricaoCurta</p>
            </div>*@
        }
    </div>
</div>

@*<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescricaoCurta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescricaoDetalhada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagemUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagemThumbnailUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsLanchePreferido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmEstoque)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescricaoCurta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescricaoDetalhada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagemUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagemThumbnailUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsLanchePreferido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmEstoque)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.CategoriaNome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.LancheId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.LancheId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LancheId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>*@